# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
pod 'AFNetworking', '~> 2.0'

target 'bookManager' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bookManager

  target 'bookManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bookManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
